name: publish-working-docs

# Controls when the action will run.
on:
  # Remark: This is used by marionbarker fork, use it to auto-deploy when updating working-docs
  # Remark: Next 2 lines triggers the workflow on push events but only for the master (which is updated post PR to loopdocs from working-docs) or working-docs branch
  push:
    branches: [ master | working-docs ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs build

      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: site
